[package]
name = "logger_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
liblogger = { path = "../liblogger" }
liblogger_macros = { path = "../liblogger_macros" }
rand = "0.8"
uuid = { version = "1.4", features = ["v4"] }
prometheus = "0.13"
psutil = "3.2"
